import { expect, test, type Page } from '@playwright/test'

/**
 * P6 brain inspector. All structure comes from the live backend (`/api/circuits/escape_v1/*`,
 * read from the P2 artifact); only the "backend unavailable" case intercepts requests.
 */

async function openInspector(page: Page, query = 'pace=5'): Promise<void> {
  await page.goto(`/?${query}#inspector`)
  await expect(page.getByTestId('inspector-view')).toBeVisible()
  await expect(page.getByTestId('circuit-graph')).toHaveAttribute('data-node-count', '286')
  await expect(page.getByTestId('circuit-graph')).toHaveAttribute('data-edge-count', '932')
}

async function searchNeuron(page: Page, neuronId: string): Promise<void> {
  await page.getByTestId('inspector-search').fill(neuronId)
  await page.getByTestId('inspector-search-submit').click()
}

async function runLooming(page: Page, direction: 'left' | 'center' | 'right', intensity: number): Promise<void> {
  await page.getByTestId(`inspector-direction-${direction}`).click()
  await page.getByTestId('inspector-intensity').fill(String(intensity))
  await page.getByTestId('inspector-run-looming').click()
  await expect(page.getByTestId('replay-step-label')).toHaveText('step 0 / 30', { timeout: 20_000 })
}

test.describe('P6 brain inspector', () => {
  test('opens from the tab and renders the whole escape_v1 circuit', async ({ page }) => {
    await page.goto('/?pace=5')
    await page.getByTestId('tab-inspector').click()
    await expect(page.getByTestId('inspector-view')).toBeVisible()
    await expect(page).toHaveURL(/#inspector$/)
    await expect(page.getByTestId('circuit-graph')).toHaveAttribute('data-node-count', '286')
    await expect(page.locator('[data-testid^="node-"]')).toHaveCount(286)
    await expect(page.locator('[data-testid^="edge-hit-"]')).toHaveCount(932)
    await expect(page.getByTestId('inspector-view')).toContainText('286 neurons · 932 edges · male-cns v1.0')
    await expect(page.getByTestId('node-10010')).toHaveAttribute('data-cell-type', 'DNp01')
    await expect(page.getByTestId('node-12032')).toHaveAttribute('data-cell-type', 'LC4')
    await page.getByTestId('tab-demo').click()
    await expect(page.getByTestId('environment-panel')).toBeVisible()
  })

  test('zoom controls and panning', async ({ page }) => {
    await openInspector(page)
    await expect(page.getByTestId('zoom-level')).toHaveText('×1.00')
    await page.getByTestId('zoom-in').click()
    await expect(page.getByTestId('zoom-level')).toHaveText('×1.40')
    const box = await page.getByTestId('circuit-graph').locator('svg').boundingBox()
    if (!box) throw new Error('graph svg not laid out')
    await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2)
    await page.mouse.down()
    await page.mouse.move(box.x + box.width / 2 + 120, box.y + box.height / 2 + 40, { steps: 6 })
    await page.mouse.up()
    await expect(page.getByTestId('circuit-graph').locator('svg > g').first()).toHaveAttribute('transform', /translate\(/)
    await page.getByTestId('zoom-reset').click()
    await expect(page.getByTestId('zoom-level')).toHaveText('×1.00')
  })

  test('hovering a neuron shows its biological identity', async ({ page }) => {
    await openInspector(page)
    await page.getByTestId('node-10010').hover()
    await expect(page.getByTestId('graph-tooltip')).toContainText('neuron 10010 · DNp01')
    await expect(page.getByTestId('graph-tooltip')).toContainText('male-cns v1.0 (biological identity)')
  })

  test('search by exact neuron id selects the neuron; unknown ids are reported', async ({ page }) => {
    await openInspector(page)
    await searchNeuron(page, '10010')
    await expect(page.getByTestId('inspector-search-message')).toHaveText('Neuron 10010 (DNp01) selected.')
    await expect(page.getByTestId('neuron-inspector')).toHaveAttribute('data-neuron-id', '10010')
    await expect(page.getByTestId('node-10010')).toHaveAttribute('data-selected', 'true')
    await expect(page.getByTestId('zoom-level')).toHaveText('×2.60')
    await searchNeuron(page, '999999')
    await expect(page.getByTestId('inspector-search-message')).toContainText('No neuron with id "999999" in the loaded circuit escape_v1')
  })

  test('cell-type search highlights only loaded neurons of that type', async ({ page }) => {
    await openInspector(page)
    const options = await page.getByTestId('inspector-cell-type').locator('option').allTextContents()
    expect(options).toEqual(['all cell types', 'DNp01', 'LC4', 'LPLC2'])
    await page.getByTestId('inspector-cell-type').selectOption('LC4')
    await expect(page.getByTestId('inspector-search-message')).toHaveText('126 LC4 neuron(s) in the loaded circuit are highlighted.')
    await expect(page.locator('[data-testid^="node-"][data-highlighted="true"]')).toHaveCount(126)
    await page.getByTestId('inspector-cell-type').selectOption('')
    await expect(page.locator('[data-testid^="node-"][data-highlighted="true"]')).toHaveCount(0)
  })

  test('neuron inspector separates biological metadata from circuit metadata', async ({ page }) => {
    await openInspector(page)
    await page.getByTestId('node-12032').dispatchEvent('click')
    const inspector = page.getByTestId('neuron-inspector')
    await expect(inspector).toHaveAttribute('data-neuron-id', '12032')
    const bio = page.getByTestId('biological-metadata')
    await expect(bio).toContainText('BIOLOGICAL METADATA')
    await expect(page.getByTestId('bio-cell-type')).toHaveText('LC4')
    await expect(page.getByTestId('bio-cell-class')).toHaveText('Not available')
    await expect(page.getByTestId('bio-nt')).toHaveText('acetylcholine')
    await expect(bio).toContainText('male-cns')
    await expect(bio).toContainText('v1.0')
    const circuit = page.getByTestId('circuit-metadata')
    await expect(circuit).toContainText('CIRCUIT / SIMULATION METADATA')
    await expect(circuit).toContainText('minimum_hop_from_seed')
    await expect(circuit).toContainText('is_seed')
    await expect(circuit).toContainText('is_target')
    await expect(circuit).toContainText('sensory')
    await expect(page.getByTestId('simulated-state')).toContainText('SIMULATED STATE')
    await expect(page.getByTestId('sim-state-empty')).toBeVisible()
    await expect(page.getByTestId('connectivity-inspector')).toContainText('Connections within loaded circuit')
    await expect(page.getByTestId('neighbors-upstream')).toHaveAttribute('data-total', '1')
    await expect(page.getByTestId('neighbors-downstream')).toHaveAttribute('data-total', '2')
    await expect(page.getByTestId('neighbor-downstream-10010')).toContainText('DNp01')
  })

  test('edge inspector shows the biological structural connection and the computational weight', async ({ page }) => {
    await openInspector(page)
    await page.getByTestId('edge-hit-12032-10010').dispatchEvent('click')
    const edge = page.getByTestId('edge-inspector')
    await expect(edge).toHaveAttribute('data-pre', '12032')
    await expect(edge).toHaveAttribute('data-post', '10010')
    await expect(page.getByTestId('edge-label')).toHaveText('BIOLOGICAL STRUCTURAL CONNECTION')
    await expect(edge).toContainText('FROM')
    await expect(edge).toContainText('TO')
    await expect(page.getByTestId('edge-synapse-count')).toHaveText('62')
    await expect(edge).toContainText('Biological structural observation')
    await expect(edge).toContainText('male-cns v1.0')
    await expect(edge).toContainText('escape_v1')
    await expect(page.getByTestId('edge-circuit-hash')).toHaveText(/^db7c46e6a165/)
    const weight = page.getByTestId('edge-simulation-weight')
    await expect(weight).toContainText('COMPUTATIONAL SIMULATION WEIGHT')
    await expect(weight).toContainText('Computational transformation')
    await expect(weight).toContainText('log1p(synapse_count) × 1')
    await expect(page.getByTestId('edge-hit-12032-10010')).toHaveAttribute('data-selected', 'true')
  })

  test('edges can be selected from the connectivity list', async ({ page }) => {
    await openInspector(page)
    await searchNeuron(page, '10010')
    await page.getByTestId('neighbor-edge-17478-10010').click()
    await expect(page.getByTestId('edge-inspector')).toHaveAttribute('data-pre', '17478')
    await expect(page.getByTestId('edge-synapse-count')).toHaveText('86')
  })

  test('upstream / downstream highlight and clear', async ({ page }) => {
    await openInspector(page)
    await searchNeuron(page, '10010')
    await page.getByTestId('highlight-upstream').click()
    await expect(page.locator('[data-testid^="node-"][data-highlighted="true"]')).toHaveCount(156)
    await expect(page.locator('[data-testid^="edge-hit-"][data-highlighted="true"]')).toHaveCount(155)
    await page.getByTestId('highlight-downstream').click()
    await expect(page.locator('[data-testid^="node-"][data-highlighted="true"]')).toHaveCount(1)
    await expect(page.locator('[data-testid^="edge-hit-"][data-highlighted="true"]')).toHaveCount(0)
    await page.getByTestId('clear-highlight').click()
    await expect(page.locator('[data-testid^="node-"][data-highlighted="true"]')).toHaveCount(0)

    await page.getByTestId('node-12032').dispatchEvent('click')
    await page.getByTestId('highlight-downstream').click()
    await expect(page.locator('[data-testid^="node-"][data-highlighted="true"]')).toHaveCount(3)
    await expect(page.locator('[data-testid^="edge-hit-"][data-highlighted="true"]')).toHaveCount(2)
  })

  test('run simulation from the inspector, then play the activity to the end', async ({ page }) => {
    await openInspector(page)
    await expect(page.getByTestId('replay-empty')).toBeVisible()
    await runLooming(page, 'center', 0.5)
    await expect(page.getByTestId('replay-run-meta')).toContainText('ESCAPE')
    await expect(page.getByTestId('replay-run-meta')).toContainText('GF activity Both')
    await page.getByTestId('replay-play').click()
    await expect(page.getByTestId('replay-step-label')).toHaveText('step 30 / 30', { timeout: 15_000 })
    await expect(page.getByTestId('replay-play')).toBeEnabled()
    await expect(page.getByTestId('replay-pause')).toBeDisabled()
  })

  test('pause stops the replay', async ({ page }) => {
    await openInspector(page, 'pace=500')
    await runLooming(page, 'center', 1)
    await page.getByTestId('replay-play').click()
    await expect(page.getByTestId('replay-step-label')).not.toHaveText('step 0 / 30')
    await page.getByTestId('replay-pause').click()
    const frozen = await page.getByTestId('replay-step-label').textContent()
    await page.waitForTimeout(1200)
    await expect(page.getByTestId('replay-step-label')).toHaveText(frozen ?? '')
    await expect(page.getByTestId('replay-pause')).toBeDisabled()
  })

  test('step / slider / reset drive per-neuron SIMULATED state on the graph and in the inspector', async ({ page }) => {
    await openInspector(page)
    await runLooming(page, 'center', 0.5)
    await searchNeuron(page, '10010')
    await expect(page.getByTestId('sim-state')).toHaveText('inactive')
    for (let i = 0; i < 3; i += 1) await page.getByTestId('replay-step').click()
    await expect(page.getByTestId('replay-step-label')).toHaveText('step 3 / 30')
    await expect(page.getByTestId('node-12032')).toHaveAttribute('data-sim-state', 'fired')
    await expect(page.getByTestId('node-10010')).toHaveAttribute('data-sim-state', 'inactive')
    await expect(page.getByTestId('replay-fired-count')).toHaveText('284 simulated spikes')
    await page.getByTestId('replay-step').click()
    await expect(page.getByTestId('replay-step-label')).toHaveText('step 4 / 30')
    await expect(page.getByTestId('node-10010')).toHaveAttribute('data-sim-state', 'fired')
    await expect(page.getByTestId('node-10001')).toHaveAttribute('data-sim-state', 'fired')
    await expect(page.getByTestId('node-12032')).toHaveAttribute('data-sim-state', 'refractory')
    await expect(page.getByTestId('sim-fired')).toHaveText('true')
    await expect(page.getByTestId('sim-refractory')).toContainText('yes (2 step(s) left)')
    await expect(page.getByTestId('sim-potential')).toHaveText('0.0000')
    await expect(page.getByTestId('simulated-state')).toContainText('not a measured neural recording')
    await page.getByTestId('replay-slider').fill('5')
    await expect(page.getByTestId('replay-step-label')).toHaveText('step 5 / 30')
    await expect(page.getByTestId('node-10010')).toHaveAttribute('data-sim-state', 'refractory')
    await page.getByTestId('replay-step-back').click()
    await expect(page.getByTestId('replay-step-label')).toHaveText('step 4 / 30')
    await page.getByTestId('replay-reset').click()
    await expect(page.getByTestId('replay-step-label')).toHaveText('step 0 / 30')
    await expect(page.getByTestId('node-10010')).toHaveAttribute('data-sim-state', 'inactive')
    await expect(page.getByTestId('sim-state')).toHaveText('inactive')
  })

  test('scientific labels keep structure, simulation and interpretation distinguishable', async ({ page }) => {
    await openInspector(page)
    const view = page.getByTestId('inspector-view')
    await expect(view).toContainText('BIOLOGICAL STRUCTURE = neuron identity + structural edges')
    await expect(view).toContainText('SIMULATED ACTIVITY = firing / membrane potential')
    await expect(view).toContainText('COMPUTATIONAL INTERPRETATION = looming mapping + decoder')
    const legend = page.getByTestId('inspector-legend')
    await expect(legend).toContainText('BIOLOGICAL DATA')
    await expect(legend).toContainText('SIMULATED')
    await expect(legend).toContainText('STRUCTURAL CONNECTION — BIOLOGICAL DATA')
    await expect(page.getByTestId('replay-controls')).toContainText('SIMULATED STATE')
    await expect(page.getByTestId('circuit-graph')).toContainText('BIOLOGICAL STRUCTURE')
    await expect(page.getByTestId('disclaimer')).toContainText('NEURAL ACTIVITY IS SIMULATED')
  })

  test('provenance panel reports dataset, canonical graph, loaded circuit, hash, status and citations', async ({ page }) => {
    await openInspector(page)
    const prov = page.getByTestId('provenance-panel')
    await expect(page.getByTestId('prov-dataset')).toHaveText('MaleCNS v1.0')
    await expect(page.getByTestId('prov-source-count')).toHaveText('≈166,700 neurons')
    await expect(prov).toContainText('status == "Traced"')
    await expect(page.getByTestId('prov-canonical-neurons')).toHaveText('165,122')
    await expect(page.getByTestId('prov-canonical-connections')).toHaveText('25,563,197')
    await expect(page.getByTestId('prov-loaded')).toContainText('escape_v1')
    await expect(page.getByTestId('prov-loaded')).toContainText('286 neurons')
    await expect(page.getByTestId('prov-loaded')).toContainText('932 edges')
    await expect(page.getByTestId('prov-hash')).toContainText('db7c46e6a165354d7aed499525e303131bd8d6367e492b2e4fc31117cdc2c78d')
    await expect(page.getByTestId('prov-hash')).toContainText('verified')
    await expect(page.getByTestId('prov-status')).toContainText('PARTIALLY SUPPORTED')
    await expect(page.getByTestId('prov-note')).toContainText('NOT the complete MaleCNS neuron census')
    await expect(prov).toContainText('CC-BY 4.0')
    await expect(page.getByTestId('prov-citations').getByRole('listitem')).toHaveCount(7)
    await expect(prov).toContainText('Klapoetke')
  })

  test('backend unavailable for the circuit API is reported, nothing is drawn', async ({ page }) => {
    await page.route('**/api/circuits/**', (route) => route.abort('connectionrefused'))
    await page.goto('/?pace=5#inspector')
    await expect(page.getByTestId('inspector-error')).toBeVisible()
    await expect(page.locator('[data-testid^="node-"]')).toHaveCount(0)
  })
})
